version: '3.9'
services:
  ambassador_backend:
    build: .
    ports:
      - 8003:8000
    volumes:
      - .:/app
    depends_on:
      - ambassador_db
      - redis
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - ambassador
      - users

  ambassador_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ifix
      MYSQL_PASSWORD: ifix
    volumes:
      - ./storage/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - ambassador

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador

networks:
  users:
    external:
      name: users
  ambassador:
