version: '3.9'
services:
  checkout_backend:
    build: .
    ports:
      - 8002:8000
    volumes:
      - .:/app
    depends_on:
      - checkout_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - checkout
      - users

  checkout_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ifix
      MYSQL_PASSWORD: ifix
    volumes:
      - ./storage/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - checkout

networks:
  users:
    external:
      name: users
  checkout:
