version: '3.9'
services:
  users_backend:
    build: .
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - users_db
    command: 'php artisan serve --host=0.0.0.0'

  users_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ifix
      MYSQL_PASSWORD: ifix
    volumes:
      - ./storage/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./storage/dbdata:/var/lib/mysql
