version: '3.9'
services:
  users_backend:
    container_name: users_ms
    build: .
    volumes:
      - .:/app
    depends_on:
      - users_db
    command: 'php artisan serve --host=0.0.0.0'
    networks:
      - users

  users_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ifix
      MYSQL_PASSWORD: ifix
    networks:
      - users
    volumes:
      - ./storage/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./storage/dbdata:/var/lib/mysql

networks:
  users:
    name: users
